Update CODE_OF_CONDUCT.md
vesoft-inc/nebula pull request #4468
Opened 2022-07-27 06:27 UTC by tian-zhong

Code of Conduct typically means how contributor should behave in this community. The current contents here are helpful coding syle guide.
It is also best to rename the filename to "CODE_STYLE_GUIDE.md"

## What type of PR is this?
- [ ] bug
- [ ] feature
- [ ] enhancement

## What problem(s) does this PR solve?
#### Issue(s) number: 

#### Description:

## How do you solve it?

## Special notes for your reviewer, ex. impact of this fix, design document, etc:

## Checklist:
Tests:
- [ ] Unit test(positive and negative cases)
- [ ] Function test
- [ ] Performance test
- [ ] N/A

Affects:
- [ ] Documentation affected (Please add the label if documentation needs to be modified.)
- [ ] Incompatibility (If it breaks the compatibility, please describe it and add the label.）
- [ ] If it's needed to cherry-pick (If cherry-pick to some branches is required, please label the destination version(s).)
- [ ] Performance impacted: Consumes more CPU/Memory

## Release notes:

Please confirm whether to be reflected in release notes and how to describe:
> ex. Fixed the bug .....

2022-07-27 06:27 UTC, CLAassistant commented
[![CLA assistant check](https://cla-assistant.io/pull/badge/not_signed)](https://cla-assistant.io/vesoft-inc/nebula?pullRequest=4468) <br/>Thank you for your submission! We really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla-assistant.io/vesoft-inc/nebula?pullRequest=4468) before we can accept your contribution.<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla-assistant.io/check/vesoft-inc/nebula?pullRequest=4468) it.</sub>

2022-07-29 01:53 UTC, Sophie-Xie approved these changes

2022-07-29 05:04 UTC, wey-gu approved these changes

2022-07-29 05:05 UTC, wey-gu requested changes
Could you please change the file name, too?

2022-07-29 07:04 UTC, wey-gu approved these changes
LGTM, Thanks!

2022-07-29 08:16 UTC, Sophie-Xie approved these changes

2022-07-29 10:37 UTC, merged